version: "3"

services:
  proxy:
    build: "./nginx"
    ports:
      - 8000:8000
    environment:
      - HOSTS=http://my-app2:3000,http://my-app:3000
    volumes:
      - ./nginx:/app/nginx

  postgres:
    image: postgres:9.6.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
    - "nodeapp_test:/var/lib/postgresql/data"

  my-app:
    build: ./app
    depends_on:
      - postgres
    volumes:
      - ./app:/app/

  my-app2:
    build: ./app
    depends_on:
      - postgres
    volumes:
      - ./app:/app/

volumes:
  nodeapp_test: